export const DEFAULT_COLLEGES = [
  "ACS International India Pvt. Ltd.",
  "Agnel Institute of of Technology and Design",
  "ASM's IBMR Pune Institute of Management & Research",
  "Ballari Institute of Technology & Management",
  "Bapuji Salunkhe Institute of Engineering and Technology",
  "Bharatiya Vidya Bhavan's Sardar Patel Institute of Technology (SPIT)",
  "College Of Engineering & Tech, Akola",
  "DKTE’S Yashwantrao Chavan Polytechnic",
  "Dnyanshree Institute of Technology",
  "Dr. DY Patil School of Science & Technology",
  "Dr. J. J. Magdum College of Engineering",
  "Dy Patil University campus , VPSM",
  "Guru Nanak Dev Engineering College Bidar Karnataka",
  "Ideal Institute Of Technology",
  "IES Group Of Institutions,Bhopal",
  "Indira College of commerce and Science",
  "Indira College of Engineering and Management",
  "Indira Global school of Business",
  "Indira Group of Institution",
  "Indira University - Pune",
  "Institute for Furture Education Entrepreneurship and Leadership",
  "International School of Management Excellence",
  "ISBR Business School",
  "KDK College of Engineering, Nagpur",
  "LEAD College of Management",
  "Lexicon MILE - Management Institute of Leadership and Excellence",
  "Maharaja Institute of Technology Mysore",
  "Mauli College of Engineering & Technology",
  "Mulshi institute of business management",
  "Nagpur Institute of Technology",
  "NCRD, Sterling Institue of Management Studies",
  "P. R. Pote Patil College of Engineering and Management",
  "Prof.Ram Meghe Institute of Technology & Research",
  "Pune District Education Association College Of Engineering",
  "Ramachandran International Institute of Management",
  "SAGE University",
  "Sandeep Institute of Technology and Research Centre",
  "Sandip Institute of Technology and Research Centre",
  "Sanjivani College of Engineering, Kopargaon",
  "Sanjivani institute of management studies",
  "Sanjivani University",
  "School of Information Technology",
  "sharad institute of technology",
  "Sharad Institute of Technology College of Engineering, Ichalkaranji (Kolhapur)",
  "Sharda University",
  "Shri Neminath Jain Brahmacharyashram",
  "Shri Ramdeobaba College of Engineering and Management",
  "Sri Eshwar College of Engineering",
  "Vishwaniketan's Institute of Management Entrepreneurship and Engineering Technology",
  "YSPM Yashoda Technical Campus"
];
